# Generated by Django 4.2.11 on 2024-04-07 09:55

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.recipe_image_file_path),
        ),
    ]
